navigation/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('navigation.views',
    url(r'^$', 'main', name='main'),
    url(r'^search_results/$', 'search_results', name='search_results'),
)

observers/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('observers.views',
    url(r'^stat-nablyudatelem/$', 'signup', name='signup'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
from cms.sitemaps import CMSSitemap

admin.autodiscover()

# TODO: sitemap doesn't work yet (because of redirect to sitemap.xml/) - see APPEND_SLASH
urlpatterns = patterns('',
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}),
    (r'^admin/', include(admin.site.urls)),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    url(r'^', include('navigation.urls')),
    url(r'^', include('observers.urls')),
    (r'^tinymce/', include('tinymce.urls')),

    url(r'^weblog/feeds/', include('zinnia.urls.feeds')),
    url(r'^weblog/authors/', include('zinnia.urls.authors')),
    url(r'^weblog/categories/', include('zinnia.urls.categories')),
    url(r'^weblog/', include('zinnia.urls.entries')),

    url(r'^captcha/', include('captcha.urls')),
    url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'', include('django.contrib.staticfiles.urls')),
    ) + urlpatterns

observers/models.py
from django.db import models

class Observer(models.Model):
    full_name = models.CharField(max_length=200)
    telephone = models.CharField(max_length=30)
    location = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    info = models.TextField()
    in_moscow = models.BooleanField()

observers/forms.py
from django import forms

from captcha.fields import CaptchaField

from observers.models import Observer

class ObserverSignupForm(forms.ModelForm):
    email = forms.CharField(max_length=50, required=False)
    info = forms.CharField(required=False, widget=forms.Textarea())
    #in_moscow = forms.BooleanField(required=False)
    #captcha = CaptchaField()

    class Meta:
        model = Observer
        exclude = ('in_moscow',)

navigation/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

from zinnia.models import Entry

def main(request):
    context = {
        'news': Entry.published.all()[:3],
    }
    return render_to_response('main.html', RequestContext(request, context))

def search_results(request):
    return render_to_response('search_results.html', RequestContext(request, {}))

observers/views.py
# coding=utf8
from smtplib import SMTPException

from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

from observers.forms import ObserverSignupForm

def signup(request):
    if request.POST:
        form = ObserverSignupForm(request.POST)

        if form.is_valid():
            observer = form.save(commit=False)
            observer.in_moscow = request.POST.get('in_moscow', 'yes')=='yes'
            observer.save()

            if observer.in_moscow:
                email = settings.MOSCOW_OBSERVERS_EMAIL
            else:
                email = settings.REGION_OBSERVERS_EMAIL

            message = u'ФИО: ' + observer.full_name + '\n'
            message += u'Телефон: ' + observer.telephone + '\n'
            message += u'Адрес: ' + observer.location + '\n'
            message += u'Email: ' + observer.email + '\n'
            message += u'Дополнительно: ' + observer.info + '\n'

            try:
                send_mail(u'Новый наблюдатель', message, 'gn@nabludatel.org', [email], fail_silently=False)
            except SMTPException:
                pass # TODO: write observer id to a special file

            return HttpResponseRedirect('/spasibo/')
    else:
        form = ObserverSignupForm()

    context = {'form': form}
    return render_to_response('signup.html',  context_instance=RequestContext(request, context))

templates/base.html
{% load cms_tags sekizai_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Гражданин наблюдатель | {% block title %}{% page_attribute page_title %}{% endblock %}</title>
        <meta name="description" content="Система постоянного общественного сопровождения процесса организации и проведения избирательных кампаний в государстве. {% page_attribute meta_description %}"/>
        <meta name="keywords" content="{% page_attribute meta_keywords %}"/>
        <link rel="icon" href="{{ MEDIA_URL }}favicon.ico" type="image/x-icon" />

        <!-- Framework CSS -->
        <link rel="stylesheet" href="{{ MEDIA_URL }}css/screen.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="{{ MEDIA_URL }}css/print.css" type="text/css" media="print">
        <!--[if lt IE 8]><link rel="stylesheet" href="{{ MEDIA_URL }}css/ie.css" type="text/css" media="screen, projection"><![endif]-->

        <link rel="stylesheet" href="{{ MEDIA_URL }}style.css" type="text/css" media="screen, projection">
        <!--link rel="stylesheet" href="http://www.google.com/cse/style/look/default.css" type="text/css" /-->
        <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?47"></script>
        {% render_block "css" %}

        <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-28655122-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
    </head>
    <body>
    <div id="stripeTails">
        <div id="bgContainer">
            <div class="container">

                <!-- #header -->      
                <div id="header" class="span-24 last">
                    <div class="span-6">
                        <a id="logo" href="/">
                            <img alt="Гражданин Наблюдатель" src="{{ MEDIA_URL }}images/logo.jpg">
                        </a>
                    </div>
                    <div id="headerRight" class="span-18 last">
                        <div id="headrSocial">
                            <p>Мы в соцсетях:</p>
                            <a href="https://www.facebook.com/nabludatel.org"><img src="{{ MEDIA_URL }}images/facebook.png" /></a>
                            <a href="http://vk.com/nabludatel_org"><img src="{{ MEDIA_URL }}images/vkontakte.png" /></a>
                            <a href="https://twitter.com/#!/nabludatel_org"><img src="{{ MEDIA_URL }}images/twitter.png" /></a>
                            <a href="http://nabludatel-org.livejournal.com/"><img src="{{ MEDIA_URL }}images/livejournal.png" /></a>
                        </div>
                        <!--div id="sluaghghairm">
                            Проект по наблюдению за выборами
                        </div-->
                    </div><!-- /#headerRight -->
                </div><!-- /#header -->  

                <!-- #menu --> 
                <div class="span-24 last">
                    <ul id="menu">
                        <li>
                            <a href="/">Главная</a>
                            <!--<ul id="help">
                                <li>
                                    <img class="corner_inset_left" alt="" src="{{ MEDIA_URL }}images/corner_inset_left.png"/>
                                    <a href="#">Страница 1</a>
                                    <img class="corner_inset_right" alt="" src="{{ MEDIA_URL }}images/corner_inset_right.png"/>
                                </li>
                                <li><a href="#">Страница 2</a></li>
                                <li><a href="#">Страница с&nbsp;длинным предлинным названием 3</a></li>
                                <li><a href="#">Страница 4</a></li>
                                <li class="last">
                                    <img class="corner_left" alt="" src="{{ MEDIA_URL }}images/corner_left.png"/>
                                    <img class="middle" alt="" src="{{ MEDIA_URL }}images/dot_blue.png"/>
                                    <img class="corner_right" alt="" src="{{ MEDIA_URL }}images/corner_right.png"/>
                                </li>
                            </ul>-->
                        </li>
                        <li><a href="/about/">О проекте</a></li>
                        <li><a href="/results/">Итоги выборов</a></li>
                        <li><a href="https://forum.nabludatel.org/">Форум</a></li>
                        <li><a href="/contacts/">Контакты</a></li>
                        <li><a href="/help/">Помочь проекту</a></li>
                    </ul>
                </div><!-- /#menu --> 

                <!-- #mainContent -->
                <div id="mainContent" class="span-24 last">

                    <!-- #sidebar -->
                    <div id="sidebar"  class="span-6">
                        <h3 class="side_menu_header">Для наблюдателей</h3>
                        <div class="side_section">
                            <ul id="left_menu_ul">
                                <li><a href="/who_is/">Кто такой наблюдатель</a></li>
                                <li><a href="/chto-dolzhen-delat-nablyudatel/">Что должен делать наблюдатель</a></li>
                                <li><a href="/nablyudateli-na-vyborah/">Зачем наблюдать за выборами</a></li>
                                <li><a href="/kak-stat-nablyudatelem/">Как стать наблюдателем</a></li>
                                <li><a href="/nezavisimyie-nablyudateli/">Почему именно наш проект?</a></li>
                                <li><a href="/results1/">Куда идут результаты</a></li>
                                <li><a href="/stat-nablyudatelem/">Записаться в наблюдатели</a></li>
                                <li><a href="/obuchenie-nablyudatelej/">Библиотека наблюдателя</a></li>
                            </ul>
                        </div>

                        <div>
                            <a href="http://money.yandex.ru/" class="ya_logo" target="_blank">
                                <img width="51" height="22" border="0" src="{{ MEDIA_URL }}images/ya_m.jpg" style="margin-left: 5px;"/>
                            </a>
                            <h3 class="side_menu_header">Сбор средств</h3>
                        </div>
                        <div class="side_section" id="donations">
                            <!-- Виджет сбора пожертвований -->
                            <form style="margin: 0pt; padding: 0pt;" action="https://money.yandex.ru/charity.xml" method="post">
                                <input type="hidden" name="to" value="410011201436323"/>
                                <input type="hidden" name="Company" value=""/>
                                <input type="hidden" name="CompanyLink" value=""/>
    
                                <div class="clearfix">
                                    <input type="text" id="CompanySum" name="CompanySum" value="100" size="4"/>
                                    <input type="submit" value="Отправить"/>
                                </div>
                            </form>

                            <div id="donationsInfo">
                                рублей на счет <a href="http://yaudit.org/yaudit/410011201436323">410011201436323</a>
                            </div>

                        </div>

                        <div class="clear"></div>

                        {% block side_block %}{% endblock %}

                    </div><!-- /#sidebar -->

                    <!-- #content -->
                    <div id="content"  class="prepend-1 span-17 last">
                        {% block content %}{% endblock %}
                    </div><!-- /#content -->        
                </div><!-- /#mainContent -->

                {% block page_bottom %}{% endblock %}

                <!-- #footer -->
                <div id="footer" class="span-24 last">
                    <hr />
                    <p class="span-7">&copy; Гражданин Наблюдатель, 2010-2011 </p>
                    <div class="prepend-11 span-6 last" id="search">
                        <!-- Виджет сбора пожертвований -->
                        <div id="cse-search-form" style="width: 100%;">Loading</div>
                        <script src="http://www.google.com/jsapi" type="text/javascript"></script>
                        <script type="text/javascript"> 
                            google.load('search', '1', {language : 'ru'});
                            google.setOnLoadCallback(function() {
                                var customSearchControl = new google.search.CustomSearchControl(
                                '007084942556480968662:efy46j0mxa8');

                                customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
                                var options = new google.search.DrawOptions();
                                options.enableSearchboxOnly("http://nabludatel.org/search_results");
                                customSearchControl.draw('cse-search-form', options);
                            }, true);
                        </script>
                    </div>
                </div><!-- /#footer -->

            </div><!-- /.container -->
            <div id="footerBtm"></div>
        </div><!-- /#bgContainer -->
    </div> <!-- /#stripeTails -->

    {% render_block "js" %}

    <!-- Yandex.Metrika counter -->
    <div style="display:none;"><script type="text/javascript">
    (function(w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter11820652 = new Ya.Metrika({id:11820652, enableAll: true, webvisor:true});
            }
            catch(e) { }
        });
    })(window, "yandex_metrika_callbacks");
    </script></div>
    <script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
    <noscript><div><img src="//mc.yandex.ru/watch/11820652" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>

templates/base_old.html
{% load cms_tags sekizai_tags %}
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
    <title>Гражданин Наблюдатель | {% page_attribute page_title %}</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Система постоянного общественного сопровождения процесса организации и проведения избирательных кампаний в государстве. {% page_attribute meta_description %}"/>
    <meta name="keywords" content="{% page_attribute meta_keywords %}"/>

    <link href="{{ MEDIA_URL }}css/layout.css" rel="stylesheet" type="text/css" />
    <!--[if lte IE 7]>
    <link href="{{ MEDIA_URL }}css/patches/patch_layout.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    {% render_block "css" %}
    <!--link href="{{ MEDIA_URL }}zinnia/css/screen.css" type="text/css" rel="stylesheet" /-->
    <link href="{{ MEDIA_URL }}css/style.css" type="text/css" rel="stylesheet" />
    <link rel="stylesheet" href="http://www.google.com/cse/style/look/default.css" type="text/css" />
    <script type="text/javascript" src="http://userapi.com/js/api/openapi.js?47"></script>
    <script type="text/javascript">
        VK.init({apiId: 2749623, onlyWidgets: true});
    </script>
</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="header" role="banner">
    <div class="page_margins">
        <div class="page">
            <a href="/" id="logo"><img src="{{ MEDIA_URL }}images/logo.jpg" alt="Гражданин Наблюдатель"/></a>
            <h1>
                <a href="/" id="title_link">Мы делаем выборы честными</a>
            </h1>
        </div>
    </div>
</div>

<!-- begin: main navigation #nav -->
<div id="nav" role="navigation">
  <div class="page_margins">
    <div class="page">
      <div class="hlist">
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/about/">О проекте</a></li>
            <li><a href="/results/">Итоги выборов</a></li>
            <li><a href="/library/">Библиотека наблюдателя</a></li>
            <li><a href="https://forum.nabludatel.org/">Форум</a></li>
            <li><a href="/contacts/">Контакты</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<!-- end: main navigation -->

<!-- begin: main content area #main -->
<div id="main">
    <div class="page_margins">
        <div class="page">
            <!-- begin: #col1 - first float column -->
            <div id="col1" role="complementary">
                <div id="col1_content" class="clearfix">
                    <h3 class="side_menu_header">Для наблюдателей</h3>
                    <div class="side_section">
                        <ul id="left_menu_ul">
                            <li><a href="/who_is/">Кто такой наблюдатель</a></li>
                            <li><a href="/what_to_do/">Что должен делать наблюдатель</a></li>
                            <li><a href="/why/">Зачем наблюдать за выборами</a></li>
                            <li><a href="/how/">Как стать наблюдателем</a></li>
                            <li><a href="/why-gn/">Почему именно ГН?</a></li>
                            <li><a href="/results1/">Куда идут результаты</a></li>
                            <li><a href="/signup/">Записаться в наблюдатели</a></li>
                        </ul>

                        <div id="cse-search-form" style="width: 100%;">Loading</div>
                        <script src="http://www.google.com/jsapi" type="text/javascript"></script>
                        <script type="text/javascript"> 
                        google.load('search', '1', {language : 'ru'});
                        google.setOnLoadCallback(function() {
                            var customSearchControl = new google.search.CustomSearchControl(
                            '007084942556480968662:efy46j0mxa8');

                            customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
                            var options = new google.search.DrawOptions();
                            options.enableSearchboxOnly("http://127.0.0.1:8000/search_results");
                            customSearchControl.draw('cse-search-form', options);
                        }, true);
                        </script>
                    </div>

                    <!--
                    <h3 class="side_menu_header">Наши друзья</h3>
                    <div class="side_section">

                        <a class="link_banner" href="http://www.kartanarusheniy.ru/">
                            <img border="0" alt="КАРТА НАРУШЕНИЙ НА ВЫБОРАХ"
                                title="Карта нарушений на выборах. Совместный проект ¨Газеты.Ru¨ и Ассоциации ¨Голос¨ "
                                src="http://files.kartanarusheniy.ru/adv/240-400.gif" />
                        </a>

                        <a class="link_banner" href="http://www.golos.org">
                            <img border="0" alt="Ассоциация ¨Голос¨" title="Ассоциация ¨Голос¨"
                                    src="http://a3.sphotos.ak.fbcdn.net/hphotos-ak-ash2/150348_168941373137020_168939573137200_387318_8024140_n.jpg" />
                        </a>

                    </div>
                    -->
                </div>
            </div>
            <!-- end: #col1 -->

            <!-- begin: #col2 second float column -->
            <div id="col2" role="complementary">
                <div id="col2_content" class="clearfix">
                    <h3 class="side_menu_header attention">Сбор средств</h3>
                    <div class="side_section">
                        <!-- Виджет сбора пожертвований -->
                        <form method="post" action="https://money.yandex.ru/charity.xml" style="margin: 0; padding: 0;">
                            <input type="hidden" value="410011201436323" name="to" />
                            <input type="hidden" value="" name="Company" />
                            <input type="hidden" value="" name="CompanyLink" />
                            <input type="submit" style="margin-right: 5px;" value="Отправить" />
                            <input type="text" style="margin-right: 5px;" size="4" value="100" name="CompanySum" id="CompanySum" />
                            <span style="font: 70% Verdana, Arial, Geneva CY, Sans-Serif;"><strong>рублей</strong></span>
                            <div class="ya_account_number">на счет <a style="color: #006600; font-weight: bold;" href="http://yaudit.org/yaudit/410011201436323">410011201436323</a>&nbsp;<span style="color: #666666;"></span></div>
                            <a class="ya_logo" href="http://money.yandex.ru/"><img width="90" border="0" height="39" style="margin-left: 5px;" src="https://img.yandex.net/i/ym-logo.gif" /></a>
                        </form>
                    </div>

                    <h3 class="side_menu_header">Мы в соц. сетях</h3>
                    <div class="side_section">
                        <a href="http://nabludatel_org.livejournal.com">
                            <img width="204" border="5" height="50" alt="Гражданин наблюдатель в Живом Журнале"
                                title="ЖЖ Гражданин наблюдатель" src="http://pics.livejournal.com/djatel_2008/pic/0000e6ds" />
                        </a>
                        <div class="content">
                            <a href="http://twitter.com/nabludatel_org" class="twitter-follow-button" data-lang="ru" data-show-count="false">Читать @nabludatel_org</a>
                            <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>
                        </div>

                        <div style="margin: 10px;">
                            <div class="fb-like" data-href="https://www.facebook.com/nabludatel.org" data-send="false" data-width="250" data-show-faces="false" data-font="lucida grande"></div>
                        </div>

                        <!-- VK Widget -->
                        <div id="vk_like"></div>
                        <script type="text/javascript">
                            VK.Widgets.Like("vk_like", {type: "mini", height: 20});
                        </script>
                    </div>
                </div>
            </div>
            <!-- end: #col2 -->

            <!-- begin: #col3 static column -->
            <div id="col3" role="main">
                <div id="col3_content" class="clearfix">
                    {% block content %}{% endblock %}
                </div>
                <div id="ie_clearing">&nbsp;</div>
                <!-- End: IE Column Clearing -->
            </div>
            <!-- end: #col3 -->
        </div>
    </div>
</div>
<!-- end: #main -->

<!-- begin: #footer -->
<div id="footer" role="contentinfo">
    <div class="page_margins">
        <div class="page" style="text-align: center;">
            Гражданин Наблюдатель, 2010-2011
        </div>
    </div>
</div>


    {% render_block "js" %}
    <script type="text/javascript" src="{{ MEDIA_URL }}libs/jquery/jquery.js"></script>
    <!--script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script-->

</body>
</html>

templates/main.html
{% extends "base.html" %}

{% load cms_tags %}
{% load zinnia_tags %}

{% block side_block %}
    <!--   FAQ btn -->
    <div class="side_section">
        <a href="/faq/" title="Часто задаваемые Вопросы"><img src="{{ MEDIA_URL }}images/faq.jpg" width="230" height="47" /></a>
    </div>
{% endblock %}


{% block content %}

    <a href="{% url signup %}" id="banner">
        &laquo;Гражданин наблюдатель&raquo;&nbsp;&mdash; некоммерческий, непартийный проект по&nbsp;наблюдению
        за&nbsp;законностью хода выборов в&nbsp;России.<br />
        <strong>Нам нужны новые лица в&nbsp;команде.</strong> Присоединяйтесь!
    </a>

{% endblock %}

{% block page_bottom %}
    <!-- #news -->
    <div id="news" class="span-24 last">
        <a href="{% url zinnia_entry_archive_index %}">
            <h1 id="newsHeader">Новости</h1>
        </a>
        <div class="newsBlock span-8">
            <small>{{ news.0.creation_date|date:"j.n.Y" }}</small>
            <h3><a href="{{ news.0.get_absolute_url }}">{{ news.0.title }}</a></h3>
            {{ news.0.html_content|truncatewords_html:50|safe }}
        </div>
        <div class="newsBlock span-8">
            <small>{{ news.1.creation_date|date:"j.n.Y" }}</small>
            <h3><a href="{{ news.1.get_absolute_url }}">{{ news.1.title }}</a></h3>
            {{ news.1.html_content|truncatewords_html:50|safe }}
        </div>
        <div class="newsBlock span-8 last"><!-- ПРОГРАММИСТУ, ВАЖНО: здесь должен идти счетчик, который добавит к третьему  последнему блоку класс .last, он убирает границу у элемента -->
            <small>{{ news.2.creation_date|date:"j.n.Y" }}</small>
            <h3><a href="{{ news.2.get_absolute_url }}">{{ news.2.title }}</a></h3>
            {{ news.2.html_content|truncatewords_html:50|safe }}
        </div>
    </div><!-- /#news -->
    
    <!--<a href="{% url zinnia_entry_latest_feed %}" class="feeds">RSS</a>
        <a href="{% url zinnia_entry_archive_index %}" title="Zinnia's Blog" rel="home">новости</a>-->
    
{% endblock %}

{% show_placeholder "template_1_content" "main" %}

{% get_recent_entries 3 "zinnia/entries_list.html" %}

templates/menu/breadcrumb.html
{% for ance in ancestors %}
<li>{% if not forloop.last %}<a href="{{ ance.get_absolute_url }}">{{ ance.get_menu_title }}</a> &raquo; {% else %}{{ ance.get_menu_title }}{% endif %}</li>
{% endfor %}

templates/menu/menu.html
{% load menu_tags %}
<ul class="main_menu">
{% for child in children %}
<li class="{% if child.selected %}selected{% endif %}{% if child.ancestor %}ancestor{% endif %}{% if child.sibling %}sibling{% endif %}{% if child.descendant %}descendant{% endif %}">
    <a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
    {% if child.children %}
    <ul>
        {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
    </ul>
    {% endif %}
</li>
{% endfor %}
</ul>

templates/signup.html
{% extends "base.html" %}

{% block content %}

<h2>Я хочу стать наблюдателем</h2>

Вы можете быть наблюдателем в том месте, где проживаете, независимо от Вашей прописки/регистрации.

<form action="{% url signup %}" method="post">
    <table>
        {% csrf_token %}
        <tr>
            <th><label for="id_full_name">Как вас зовут (ФИО полностью): <span class="red">*</span></label></th>
            <td>
                {{ form.full_name }}
                {% if form.full_name.errors %}<div style="color:red;">Введите свое имя</div>{% endif %}
            </td>
        </tr>
        <tr>
            <th><label for="id_telephone">Ваш контактный телефон: <span class="red">*</span></label></th>
            <td>
                {{ form.telephone }}
                {% if form.telephone.errors %}<div style="color:red;">Введите ваш телефон</div>{% endif %}
            </td>
        </tr>

        <tr>
            <th>
                Ваш регион: <span class="red">*</span>
            </th>
            <td>
                <input type="radio" name="in_moscow" value="yes" id="id_in_moscow" checked="true"/>
                <label for="id_in_moscow">Москва и Московская область</label>
                
                <input type="radio" name="in_moscow" value="no" id="id_not_in_moscow" />
                <label for="id_not_in_moscow">Другой регион</label>
            </td>

        </tr>

        <tr>
            <th><label for="id_location">Место жительства: <span class="red">*</span></label></th>
            <td>
                {{ form.location }}
                <div style="font-size: small;">Для жителей Москвы - район проживания, для жителей Московской области - район и населенный пункт.</div>

                {% if form.location.errors %}<div style="color:red;">Укажите район в котором проживаете</div>{% endif %}
            </td>
        </tr>
        
        <tr>
            <th><label for="id_email">Ваш адрес электронной почты: <span class="red">*</span></label></th>
            <td>
                {{ form.email }}
                {% if form.email.errors %}<div style="color:red;">Email указан неверно</div>{% endif %}
            </td>
            
        </tr>
        <tr>
            <th><label for="id_info">Дополнительно сообщаю:</label></th>
            <td>{{ form.info }}</td>
        </tr>

        <!--tr>
            <th><label for="id_captcha_1">Captcha:</label></th>
            <td>{{ form.captcha }}</td>
        </tr-->

    </table>
    <input type="submit" value="Отправить"/>
</form>

{% endblock %}

templates/users/profile.html
{% extends "base.html" %}

{% block content %}

<h2>{{ user_data.name.first_name}} {{ user_data.name.last_name}}</h2>

{{ user }}

<div>
    <img src="{{ user_data.photo }}"/>
    
</div>

<a href="{{ user_data.identity }}">Страница</a>

{% endblock %}